version: '3'

services:
    client:
        build: ./client
        ports:
            - 8080:8080
        volumes:
            - ./client:/data
        environment:
            - API_URL=http://localhost:8081/
            - CHOKIDAR_USEPOLLING=true
    server:
        build: ./server
        ports:
            - 8081:8081
        volumes:
            - ./server:/data
        depends_on:
            - db
        environment:
            - DATABASE_URL=db
    db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db
